version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: tset
      POSTGRES_DB: mysite
    volumes:
      - db-data:/var/lib/postgresql/data
      - ~/dev/db-data/psql/mysite:/db-dump

  db-admin:
    image: adminer
    container_name: pg-admin
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: mysite
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - "8080:8080"

volumes:
  db-data:
